// Some Candles — GM threat / inspiration bank.
//
// This is a plain data file, deliberately kept separate from the app's own logic so it's
// easy to read and edit on its own: add an entry, remove one, rewrite the wording, all
// without touching game rules code at all. It's loaded with a normal <script> tag before
// the main app script (see some-candles.html), which works fine fully offline since it's
// just a script include, not a network request.
//
// Each entry is GM-facing inspiration only, not something read verbatim from any existing
// property. "inspiration" is a short genre/tone tag, not a title or citation.
//
// Fields:
//   id        unique string, used to avoid repeats until the whole bank has been seen once
//   title     short label for the threat, shown in the app
//   inspiration  genre/tone tag shown under the title
//   prompt    2-3 sentences describing the situation, for the GM's own reference
//   whisper   one unsettling detail the GM can drop in before the reveal
//   readAloud a short paragraph the GM can read aloud to introduce the threat to players
const THREATS = [
    { id:'t01', title:'The Smiling Village', inspiration:'folk horror — a pagan harvest festival gone wrong',
      prompt:'A nearby settlement greets the survivors with warmth, flower crowns, and a feast, but the smiles never quite reach the eyes, and a calendar on the wall is circled in red for tonight. Something is owed to the fields before the light comes back, and outsiders make convenient offerings.',
      whisper:'Distant chanting carries on the wind, cheerful and rhythmic, like a lullaby sung backwards.',
      readAloud:'You crest the hill and the village unfolds below you, hearth-smoke curling gold against the dark. Someone rings a bell, and warm laughter drifts up to meet you, flower crowns woven fresh just this morning. A woman steps forward, arms open, smile wide as a doorway. "You made it just in time," she says. "We were hoping for guests tonight." Behind her, someone is already sharpening something long and silver. What do you do?' },
    { id:'t02', title:'The Effigy on the Hill', inspiration:'folk horror — an effigy built for a sacrifice',
      prompt:'A towering wicker or wooden figure stands half-built on a hilltop outside of town, and every day it grows a little larger, a little more finished, with room inside for exactly the number of survivors left alive.',
      whisper:'Someone has already carved names into its base. One of them is a name from your group.',
      readAloud:'On the ridge above the tree line, silhouetted black against a sky that never brightens, something enormous stands half-finished, ribs of woven branch and rope rising three stories into the dark. You can hear it creak in the wind like a ship\'s hull. As you get closer, you see the names. Dozens of them, carved deep into the wood at the base, still pale where the knife bit in. One of them, you\'re almost sure, is yours.' },
    { id:'t03', title:'The Bargain in the Wood', inspiration:'folk horror — a bargain struck in the deep woods',
      prompt:'Livestock, food, or a missing child vanish near the treeline, and the youngest or most vulnerable member of the group begins insisting they\'ve been spoken to by something kind, patient, and not remotely human.',
      whisper:'A goat (or something shaped like one) watches from just past the last tree, unblinking, for far too long.',
      readAloud:'The youngest of you doesn\'t come back from the treeline right away, and when they finally do, their eyes are somewhere else entirely. "It just wants to be friends," they whisper, smiling in a way that doesn\'t quite reach the rest of their face. Behind them, at the very edge of where your firelight gives out, something with too many legs and the patient stillness of a very old thing is watching. It does not blink. It does not need to.' },
    { id:'t04', title:'The Keeper\'s Madness', inspiration:'isolation horror — two people, one light, and encroaching madness',
      prompt:'Two survivors are sealed together in a cramped, isolated space, a lighthouse, a silo, an attic, while a strange light, gas, or smell seeps in, and one of them is starting to see (and say) things the other can\'t explain away.',
      whisper:'A low, rhythmic droning sound comes from below, in time with a light that shouldn\'t still be turning.',
      readAloud:'The light above you turns, and turns, and turns, a slow mechanical groan you\'d stopped noticing until right now, when it\'s the only sound left in the world. Your companion hasn\'t spoken in an hour. When they finally do, their voice is flat, careful, deliberate: "Did you hear that too? Just now? Tell me you heard that too." You didn\'t.' },
    { id:'t05', title:'The Old Debt of the Land', inspiration:'folk horror — land with an old, unpaid debt',
      prompt:'The place the survivors have taken shelter in was built on land with a reputation, a plague pit, a hanging tree, a drowned chapel, and the locals who are left seem to believe the debt on it was never actually paid.',
      whisper:'The soil here is colder than it should be, even near the fire.',
      readAloud:'The ground here is wrong. Not rocky, not frozen, just wrong, cold in a way that has nothing to do with the season, soft in places that should be solid. An old man in the last house on the road watches you set up camp and says, without much interest, "Folks used to bury things out past that ridge. Debts, mostly. Some of \'em still walkin\' \'em off." He doesn\'t elaborate. He doesn\'t need to.' },
    { id:'t06', title:'The Symbols in the Trees', inspiration:'found footage dread — unseen watchers in the woods',
      prompt:'Small stick figures, cairns of stones, or strange bundles of twigs appear around the survivors\' camp each morning, closer every time, though no one ever hears footsteps approaching in the night.',
      whisper:'Somewhere out past the firelight, something is very deliberately snapping twigs, one at a time, in a rhythm.',
      readAloud:'You wake to find them again: small figures of lashed twigs, hanging at eye level from branches that weren\'t there last night, close enough now that you could reach out and touch one if you dared. No footprints in the frost. No broken branches. Just the figures, a little closer to camp than yesterday, swaying gently though there is no wind at all.' },
    { id:'t07', title:'The One Who Wandered Off', inspiration:'found footage dread — the one who wandered off and came back wrong',
      prompt:'A survivor who left to scout ahead is found standing motionless, facing a corner or a wall, and can\'t explain how long they\'ve been there, what they saw, or why their hands are shaking.',
      whisper:'When asked what happened, they only ever repeat the same four or five words, verbatim, every time.',
      readAloud:'You find them exactly where you left them, except they haven\'t moved in what must be hours: facing the corner, shoulders hunched, hands trembling at their sides. When you say their name, they answer, but it takes far too long, and the words that come out are the same four words, over and over, like a groove worn into a record: "It was already there. It was already there."' },
    { id:'t08', title:'The Countdown', inspiration:'cursed media — a recording that marks whoever experiences it',
      prompt:'Something the survivors watched, read, or heard, a tape, a broadcast, a recording on the radio, has marked one of them. Something will come for that person soon, and there may be no one left to pass the curse along to this time.',
      whisper:'A wet, dragging sound echoes faintly from every screen and mirror in the building, even the broken ones.',
      readAloud:'The static clears for just a moment, just long enough for you to catch it: a voice, or something wearing one, reading numbers, backward, in a register too low to be entirely human. Whoever heard it first goes pale and won\'t say why. When you ask what\'s wrong, they only check their watch. Again. And again.' },
    { id:'t09', title:'The Well', inspiration:'cursed media — something crawling out of standing water',
      prompt:'A crawling, dripping shape drags itself, joint by joint, out of standing water toward anyone who lingers near it too long, and it moves faster than something that broken has any right to.',
      whisper:'The water nearby is always a few degrees too cold, and never quite still.',
      readAloud:'Something in the water moves, wrong, jointed at angles that don\'t belong to anything living, dragging itself up over the stone lip inch by dripping inch. It shouldn\'t be able to move that fast. It shouldn\'t be able to move at all. And yet here it comes.' },
    { id:'t10', title:'The Sinner\'s Ledger', inspiration:'moralizing killer — staged scenes as punishment for sin',
      prompt:'Someone, or something, is punishing the survivors\' pasts one transgression at a time, leaving elaborately staged scenes as warning before the next "lesson" is delivered.',
      whisper:'A note is left behind naming the next transgression to be judged, in careful, patient handwriting.',
      readAloud:'Laid out on the table, in a room none of you remember unlocking, is a scene, small, precise, deliberate, that mirrors something none of you have spoken aloud to each other. Beside it, in patient handwriting, a single line: it knows what you did. And it isn\'t finished.' },
    { id:'t11', title:'What\'s In The Box', inspiration:'moralizing killer — a delivered trophy naming who is next',
      prompt:'A delivery, container, or trophy is left where the group will find it, containing unmistakable proof of a previous victim, and a message naming exactly who\'s next.',
      whisper:'Whoever opens it can\'t say afterward exactly why they keep hearing their own name.',
      readAloud:'The box is wrapped, almost gift-like, sitting on the doorstep like it\'s always been there. Inside, wrapped in cloth gone dark and stiff, is proof, unmistakable, of somebody else\'s very bad night. Tucked beneath it, a note. One line. One name. Yours.' },
    { id:'t12', title:'The Too-Perfect Hosts', inspiration:'social horror — hospitality that curdles after dark',
      prompt:'A group of unnervingly hospitable survivors offers shelter, food, and safety, but their warmth curdles the moment the sun goes down, and their eyes occasionally lose focus mid-sentence, like something else is listening through them.',
      whisper:'One of the hosts pauses mid-conversation, smiles a moment too long, and says, "You\'re one of the good ones."',
      readAloud:'Their hospitality is immaculate: warm bread, warmer smiles, a fire already lit before you even knocked. But watch the eyes. Every so often, mid-sentence, they go soft and distant, like a radio drifting off-station, before snapping back to that same easy warmth. One of them touches your arm and says, "You\'re one of the good ones," and you have absolutely no idea what that means, or what happens to the ones who aren\'t.' },
    { id:'t13', title:'The Auction', inspiration:'social horror — being appraised and bid on by unseen buyers',
      prompt:'The survivors slowly realize they are being appraised, catalogued, or bid on by unseen "buyers," who see something valuable in what they are, not who they are.',
      whisper:'A ledger is found listing every survivor by name, alongside numbers that only make sense as a price.',
      readAloud:'You find the ledger by accident, tucked beneath a stack of ordinary papers: names, descriptions, and numbers that only make sense as a price. Your names. Your descriptions. Someone has been watching, and cataloguing, and bidding.' },
    { id:'t14', title:'The Guest Who Wasn\'t Invited', inspiration:'grief made monstrous — a shape that refuses to leave',
      prompt:'A shape, tall, black-coated, and patient, has started appearing in the same corner of every room the group sleeps in, and it always says the same thing: it isn\'t leaving, ever.',
      whisper:'A page has been found describing exactly how it gets in, and the description matches your own front door.',
      readAloud:'It\'s in the corner again. Tall, black-coated, utterly still, the shape you\'ve all started pretending not to notice. Nobody has ever seen its face. Nobody wants to. When the youngest of you finally asks it to leave, it doesn\'t move, doesn\'t speak, until much later, in a voice like a door creaking open: "I don\'t."' },
    { id:'t15', title:'The Inheritance', inspiration:'grief made monstrous — a bloodline bound to something ancient',
      prompt:'A bloodline among the survivors is bound to something ancient and covetous through a family object, name, or mark, and the eldest of that bloodline has started insisting, calmly, that it\'s already too late to stop it.',
      whisper:'A model, dollhouse, or diorama nearby is an exact miniature of the room you\'re standing in, right now.',
      readAloud:'The eldest among you says it plainly, calmly, in a voice that makes your skin crawl precisely because it isn\'t afraid: "It\'s already too late. It has been for a long time." Behind them, on the mantle, a miniature of this exact room sits gathering dust, every detail correct, including the tiny figures standing exactly where you\'re standing now.' },
    { id:'t16', title:'The Family That Isn\'t', inspiration:'grief made monstrous — a substitute wearing a lost loved one’s habits',
      prompt:'A "rescued" member of the group has been quietly mimicking the routines of someone the family lost, sitting in their chair, wearing their coat, and the resemblance is too exact to be coincidence.',
      whisper:'At night, a small, wordless hum comes from their room, in a tune no one in the group taught them.',
      readAloud:'They sit in the chair that isn\'t theirs. Wear the coat that isn\'t theirs. Hum, softly, a tune none of you taught them, in a voice that is almost, almost right. When you ask where they learned it, they look at you like the question doesn\'t make any sense at all.' },
    { id:'t17', title:'The Invitation to the Juke Joint', inspiration:'Southern gothic hunger — a roadhouse that never lets the night end',
      prompt:'Music and light spill from a roadhouse that shouldn\'t still have power, and everyone inside looks like they\'re having the best night of their lives, and none of them seem eager to let the survivors leave before sunrise.',
      whisper:'The band never stops playing the same song, over and over, note for note, and nobody inside seems to notice.',
      readAloud:'Light spills gold across the gravel from a roadhouse that has no business still having power, and the music, low, warm, unbelievably good, pulls at something in your chest you didn\'t know was hungry. Inside, everyone is laughing the way people laugh on the best night of their lives. The band never stops playing the same song. Nobody inside seems to have noticed. The door is warm to the touch, unlocked, and wide, wide open.' },
    { id:'t18', title:'The Guest Who Must Be Invited In', inspiration:'gothic hunger — something ancient that must be invited across the threshold',
      prompt:'Something ancient, hungry, and very charming cannot cross a threshold uninvited, but it is patient, well-spoken, and remarkably good at getting invited anyway.',
      whisper:'It already knows everyone\'s name, and uses them like it\'s known your group for years.',
      readAloud:'He\'s charming, in the old way, the kind of charming that makes you forget to ask questions. He already knows your names. He already knows far more than he should. And when he pauses at the threshold, waiting, smiling, patient as a held breath, you realize, all at once, that he has been waiting for one of you to say the word.' },
    { id:'t19', title:'Something Big Is Hunting', inspiration:'predator terror — something vast hunting in open water or grass',
      prompt:'A predator, in dark water, tall grass, or an empty stretch of road, is picking off survivors one at a time, and each confirmed kill makes clear it is bigger, and smarter, than anyone assumed.',
      whisper:'A low, resonant sound, almost like a heartbeat, rolls through the ground or the water right before it strikes.',
      readAloud:'The water goes still, all at once, in a way that water does not do on its own. Something vast moves just beneath the surface, patient, unbothered, cataloguing you. A low sound rolls up through the ground beneath your feet, felt more than heard, and every animal for a mile has already gone silent.' },
    { id:'t20', title:'The Ones Who Won\'t Believe You', inspiration:'predator terror — a rival group that refuses to believe the danger is real',
      prompt:'A rival group of survivors refuses to believe, or refuses to admit, that the danger is real, because acknowledging it would mean giving up a safe haven, a supply cache, or a leader\'s authority.',
      whisper:'Their leader keeps insisting everything\'s fine, even as their own people quietly start disappearing.',
      readAloud:'Their leader waves you off with a laugh that doesn\'t reach his eyes. "Everything\'s fine here," he says, for the third time, while behind him, someone quietly, carefully, marks another name off a list. Nobody else seems to notice how short that list has gotten.' },
    { id:'t21', title:'The Aristocrat With No Reflection', inspiration:'vampiric bargain — a charming host with no reflection',
      prompt:'A charming, cultured stranger offers sanctuary in a grand, decaying home, and each night invites exactly one member of the group to stay a little later, and talk a little longer, than the others.',
      whisper:'Every mirror in the house reflects the room, the furniture, the candles... but never quite the host.',
      readAloud:'The house is grand, and cold, and beautiful in the way that old, dying things are beautiful. Your host pours the wine himself, smiling with teeth just a little too white, an accent from somewhere that no longer exists. "Stay," he says, to just one of you, in a voice that curls warm around the word. "The others can go on ahead." Behind him, the mirror over the fireplace reflects the room, the candles, the wine, everything except him.' },
    { id:'t22', title:'The Brides in the Dark', inspiration:'vampiric bargain — a fresh nest of something ancient nearby',
      prompt:'Something ancient has taken a fresh nest nearby, and every "missing persons" report from before the world went dark traces back to the very same address.',
      whisper:'Laughter, soft and layered, three voices overlapping as one, drifts from an upstairs room that should be empty.',
      readAloud:'Laughter drifts down from the floor above, soft, layered, three voices overlapping into one sound that raises every hair on your arms. The room up there has been locked for years. It is not locked now.' },
    { id:'t23', title:'The Lord of the Mists', inspiration:'gothic curse — a domain that traps travelers in a loop around its lonely lord',
      prompt:'The land itself seems to trap the survivors in a loop, roads doubling back, landmarks repeating, drawing them inevitably toward a castle or manor ruled by something old, proud, and desperately lonely.',
      whisper:'A raven, or a wolf, or a patch of fog seems to be herding you, gently but insistently, toward the same road each time.',
      readAloud:'The road bends the same way it bent an hour ago. The same crooked tree. The same broken fence post. A raven watches from the wire, tilting its head, and when you finally, finally crest the rise, the castle is exactly where you always somehow knew it would be, waiting, the way it has always been waiting.' },
    { id:'t24', title:'The Moon Remembers', inspiration:'gothic curse — a transformation tied to the phase of the moon',
      prompt:'Something in the group, or something nearby, changes with the phase of the moon, and the transformation is getting harder to hide, predict, or control with each cycle.',
      whisper:'Claw marks are found gouged into the inside of a locked door, from someone who swears they never left their bed.',
      readAloud:'The moon rises, fat and full and far too bright, and something changes in the room. A chair scrapes back. A voice you know goes low and strange. Later, someone finds claw marks gouged into the inside of a locked door, and no one wants to ask the obvious question out loud.' },
    { id:'t25', title:'The School That Kept a Secret', inspiration:'institutional horror — an institution that hid something dangerous for the children’s own good',
      prompt:'An abandoned academy or institution hid something dangerous in its walls for generations "for the children\'s own good," and whatever it was never stopped growing hungrier in the dark.',
      whisper:'A locked door on the lowest level has fresh scratch marks on the outside, not the inside.',
      readAloud:'The halls are long, and dark, and smell faintly of chalk dust and something else, something metallic, something old. A door at the end of the lowest corridor is bolted three times over, and the scratches on it run the wrong direction. Not trying to get in. Trying to get out.' },
    { id:'t26', title:'The Mark Left Behind', inspiration:'institutional horror — a mark that makes its bearer recognizable to something in the dark',
      prompt:'A brand, scar, or symbol has appeared on a survivor\'s skin, and every creature encountered in the dark since seems to recognize it, and them, immediately.',
      whisper:'It only ever aches, faintly, right before something finds you.',
      readAloud:'It doesn\'t hurt, not exactly, more like a low hum beneath the skin, a brand none of you remember getting. But every time something moves in the dark just past the light, it turns to look at exactly the one who bears it, like it already knows their name.' },
    { id:'t27', title:'The Sprinters', inspiration:'rage outbreak — fast, coordinated hunters instead of slow shamblers',
      prompt:'These aren\'t slow and shambling; They are fast, coordinated, and closing distance far quicker than anyone expects, hunting in packs that communicate with shrieks instead of words.',
      whisper:'A rhythmic screech, repeated three times, echoes from three different directions at once.',
      readAloud:'They don\'t shamble. They don\'t moan. They come fast, low, coordinated, closing distance before you\'ve even finished raising the alarm, shrieking to each other in a language that is almost words. By the time you hear them, they are already closer than you think.' },
    { id:'t28', title:'Patient Zero', inspiration:'rage outbreak — a hidden infection counting down to a turn',
      prompt:'A survivor was bitten, scratched, or exposed and hasn\'t told anyone yet, quietly counting down the hours until they turn, and dreading, or maybe welcoming, what comes next.',
      whisper:'They\'ve started keeping their sleeves down, even in the heat, and flinching whenever anyone touches their arm.',
      readAloud:'They\'ve been keeping their sleeve down all day, flinching whenever anyone brushes past their arm, laughing a little too quickly when someone asks if they\'re alright. When they finally roll up that sleeve, alone, in the dark, they don\'t like what they see. And neither will you.' },
    { id:'t29', title:'It Wears What You Fear', inspiration:'shape-shifting fear eater — a threat that wears whatever each person fears most',
      prompt:'The threat doesn\'t have one face; it shows each survivor whatever terrifies them most, and no two people in the group can agree on what they actually saw.',
      whisper:'A child\'s laughter echoes from a storm drain, sewer grate, or low crawlspace nearby, always just a little too deep to be a child\'s.',
      readAloud:'Ask each of you what you saw and you\'ll get a different answer: a face, a shape, a memory that shouldn\'t be able to walk. It doesn\'t matter which one is true. What matters is that it knew exactly where to look.' },
    { id:'t30', title:'The Storm Drain Sings', inspiration:'shape-shifting fear eater — something delighted whenever someone looks too closely',
      prompt:'People, especially children or the childlike, have been going missing near drains, wells, and low, dark places, and something down there is delighted every time someone gets close enough to look.',
      whisper:'A bright red balloon, or something shaped like one, bobs gently against the current, going the wrong way.',
      readAloud:'Somewhere below the street, water drips in a rhythm too even to be natural, and underneath it, faint, delighted, unmistakably a child\'s laugh, drifts up through the grate. A bright red shape bobs against the current in the dark below, moving the wrong way.' },
    { id:'t31', title:'The Facility', inspiration:'government horror — an abandoned facility that still hums with power',
      prompt:'A quietly abandoned research facility still hums faintly with power, and whatever "vanished" in its sublevels came back changed, hungry, and very possibly still listening through the walls.',
      whisper:'A radio left in a nearby room picks up a faint, rhythmic clicking on every channel, all at once.',
      readAloud:'The building has been dead for years, dark windows, rusted fences, and yet somewhere deep inside, a generator hums, low and steady, a heartbeat that shouldn\'t still be beating. On every channel your radio can find, all at once, something is clicking, patiently, rhythmically, like it\'s counting.' },
    { id:'t32', title:'The Mirror World', inspiration:'government horror — reality briefly doubling into something colder and wrong',
      prompt:'Reality seems to double for a moment at a time, familiar rooms gone cold and grey, lights flickering out of sync, something breathing softly just behind the wallpaper or under the floor.',
      whisper:'Ash, or something like it, drifts gently from the ceiling in a room that has no fire nearby.',
      readAloud:'For just a second, the room goes cold, and grey, and wrong, wallpaper peeling in a house that was fine a moment ago, and you can hear something breathing, slow and even, from a spot in the wall where nothing should be able to breathe at all. Then, just as suddenly, it\'s over. Was it?' },
    { id:'t33', title:'Hunt by Sound', inspiration:'silence-or-death predator — something that hunts by sound alone',
      prompt:'Something out there has no use for eyes; it converges instantly and violently on any noise, a generator, a dropped weapon, a crying child, all of it rings like a dinner bell.',
      whisper:'A distant shriek answers the faintest sound, every single time, closer than it was the last time.',
      readAloud:'Somewhere out past the dark, something with no need for eyes is listening, and it does not forgive noise. A dropped tool rings out. A held breath goes ragged. And from somewhere closer than it was a moment ago, something answers.' },
    { id:'t34', title:'The Blind Nest', inspiration:'silence-or-death predator — a nearby nest that will not stay quiet forever',
      prompt:'A den or nest of the creatures lies uncomfortably close by. It\'s quiet for now, but it will not stay that way if anyone speaks above a whisper.',
      whisper:'Chitinous clicking, faint but constant, comes from somewhere just underneath the floorboards.',
      readAloud:'The tunnel narrows, and the air changes, thick, and close, and full of a faint clicking that seems to come from everywhere at once. Whatever\'s nesting down here is quiet, for now. It will not stay that way if anyone so much as whispers.' },
    { id:'t35', title:'The Cook', inspiration:'moral decay — a valuable skill offered protection at a terrible cost',
      prompt:'A survivor with a rare, valuable skill, medicine, chemistry, engineering, is quietly offered protection by a dangerous rival faction, at the cost of using that skill for something they will absolutely regret.',
      whisper:'They\'ve started meeting with strangers alone, and won\'t say what they traded for the supplies they came back with.',
      readAloud:'They\'ve been slipping away at odd hours, coming back with supplies nobody wants to ask too many questions about. Tonight, you follow, and what you see, hands steady over something they clearly should not know how to make, is going to be very hard to un-see.' },
    { id:'t36', title:'The Ledger', inspiration:'moral decay — a secret debt to a dangerous faction coming due',
      prompt:'Someone in the group has been quietly trading with a dangerous faction behind everyone else\'s back, and the debt they owe is about to come due, with interest.',
      whisper:'A stranger arrives asking, very politely, for "what\'s owed," and already knows every name in the group.',
      readAloud:'A stranger arrives at the edge of camp, polite, unhurried, hat in hand, already using every one of your names like old friends. "Just here about what\'s owed," he says, pleasant as anything. Somebody in your group goes very, very quiet.' },
  { id:'t37', title:'The Long Walk Home', inspiration:'undead apocalypse — a shuffling horde that never stops coming',
    prompt:'The dead don\'t run, they don\'t think, and they don\'t quit; a slow-moving horde is grinding toward the survivors\' shelter one shambling step at a time, and there are always more of them than anyone counted.',
    whisper:'Somewhere past the fence line, a low, constant moan rises and falls like tide.',
    readAloud:'You hear them before you see them: a low, ragged moan, dozens of throats overlapping into one sound. Then the tree line moves, all of it, at once, a slow gray tide of arms and open mouths pushing through the brush. They aren\'t fast. They don\'t have to be. There are so many of them, and they are not going to stop.' },
  { id:'t38', title:'Who You Used To Be', inspiration:'undead apocalypse — a loved one turned, and no one will say it out loud',
    prompt:'Someone the group cared for didn\'t survive a bite, a scratch, a fever, and is now locked away, restrained, or simply not mentioned, while the person responsible for making the hard call keeps quiet-quiet, waiting to see if anyone else will do it first.',
    whisper:'A soft, wet shuffling comes from behind a door nobody has opened in two days.',
    readAloud:'Nobody talks about the room at the end of the hall anymore. You hear it sometimes, at night, a slow shuffle, a soft bump against the door. Someone changes the subject every time it comes up. Someone else has started sleeping with a knife under their pillow. Eventually, somebody is going to have to open that door.' },
  { id:'t39', title:'The Fortified Gate', inspiration:'undead apocalypse — a walled compound that isn\'t as safe as it looks',
    prompt:'A fortified settlement offers the survivors food, walls, and rules, run by a leader whose calm authority starts to feel less like safety and more like a cage the moment anyone tries to ask about the people who used to live there.',
    whisper:'The gate guard counts your group twice, out loud, and writes the number down in a ledger that already has too many crossed-out names.',
    readAloud:'The walls are real, and solid, and higher than anything you\'ve seen since this all started. The man at the gate smiles like he means it. "You\'ll like it here," he says, writing your names in a ledger thick with other names, most of them crossed out. Somewhere behind the walls, faint and constant, something is still moaning. Nobody inside seems to notice anymore.' },
  { id:'t40', title:'No Clean Bites', inspiration:'undead apocalypse — the infection spreads faster than anyone admits',
    prompt:'Whatever is turning the dead spreads through the smallest contact, a scratch, a cough, a shared cup, and the group is starting to eye each other\'s smallest injuries with a suspicion that might get someone killed long before any of them actually turn.',
    whisper:'Someone in the group has started wearing long sleeves regardless of the heat, and won\'t explain why.',
    readAloud:'"It\'s just a scrape," they say, pulling their sleeve back down before anyone can look closer. Nobody quite believes them anymore. You\'ve all seen how fast it happens, how small the mark can be. Nobody wants to be the one who says it out loud. But somebody is going to have to check.' },
  { id:'t41', title:'The Thing Beneath the Skin', inspiration:'cosmic dread — a presence too vast to be seen all at once',
    prompt:'Something vast and utterly indifferent to human survival has begun bending the world near the survivors just by being close, cracked geometry, wrong colors, animals going mad, and understanding any more of it than a glimpse threatens to cost someone their mind.',
    whisper:'Every compass in the group now points confidently in a direction that isn\'t north.',
    readAloud:'The compass needle doesn\'t waver, doesn\'t spin, just points, calm and certain, at a patch of empty horizon that makes your teeth ache to look at. Something out there is enormous, and old, and entirely uninterested in whether you understand it. The birds stopped singing an hour ago. They haven\'t started again.' },
  { id:'t42', title:'The Star That Fell Wrong', inspiration:'cosmic dread — an impossible object that shouldn\'t still be warm',
    prompt:'Something fell from the sky and didn\'t behave like a meteor should: it\'s still warm days later, animals avoid the crater entirely, and anyone who gets too close reports the same impossible dream that night.',
    whisper:'Static on every radio in range resolves, faintly, into a single repeated word none of you recognize.',
    readAloud:'The crater is too clean, too round, still faintly warm to the touch days after it fell. None of the local animals will go near it. Last night, three of you had the exact same dream, and none of you can quite remember what it was, only that you woke up already knowing the word for it.' },
  { id:'t43', title:'The Cult of the Correct Angle', inspiration:'cosmic dread — devotees who worship something that doesn\'t care about them',
    prompt:'A small, quiet cult has organized itself around worship of the thing lurking beyond the world\'s edge, and its members are unnervingly calm, almost grateful, about what they believe is coming, and eager to make the survivors grateful too.',
    whisper:'One of the cultists keeps humming the same seven notes, over and over, and it\'s starting to catch in your own head.',
    readAloud:'They don\'t shout, don\'t threaten, don\'t even seem afraid. "It doesn\'t hate you," one of them says, smiling with a patience that feels worse than any snarl. "It just doesn\'t know you\'re there. Isn\'t that better?" Behind them, painted crudely but precisely on the wall, is an angle that hurts to look directly at.' },
  { id:'t44', title:'Behind the Mask', inspiration:'slasher dread — a killer who never runs, never speaks, and never seems to tire',
    prompt:'Something in a mask, or a hood, or simply a face gone perfectly blank, has fixed on the survivors and walks toward them at an unhurried, unstoppable pace no matter how far or fast they run.',
    whisper:'It\'s always exactly one room behind you, no matter how much time you thought you gained.',
    readAloud:'You run until your lungs burn, until the distance should mean something, and when you finally look back, there it is anyway, the same unhurried walk, the same blank stare through the mask, exactly one room behind, like the running never happened at all.' },
  { id:'t45', title:'The Anniversary', inspiration:'slasher dread — a killing tied to a date the group didn\'t know mattered',
    prompt:'Tonight is the anniversary of something terrible that happened in this exact place, and whatever is hunting the survivors seems to believe they\'re meant to play a part in reenacting it.',
    whisper:'A local, if any can be found, goes pale at the date and refuses to say anything more.',
    readAloud:'"Tonight?" the old woman says, and her face goes the color of ash. "You\'re staying here tonight?" She won\'t say anything else, not the date, not the name, just gathers her things and leaves faster than her legs look like they should carry her. Somewhere in town, a clock you didn\'t know still worked chimes the hour.' },
  { id:'t46', title:'One of Us Isn\'t', inspiration:'slasher dread — the killer has been traveling with the group the whole time',
    prompt:'The killer isn\'t outside the group\'s shelter anymore; the pattern of who\'s been where, and when, only makes sense if it\'s someone already trusted, already close, already sleeping in the same room tonight.',
    whisper:'The timeline only adds up one way, and nobody wants to say the name it points to out loud.',
    readAloud:'You lay it out in your head one more time: who was where, who was missing, when. It only adds up one way. You look around the fire at the faces you trust, the ones who\'ve kept you alive this far, and you realize you\'re going to have to decide, tonight, which of them you\'re wrong about.' },
  { id:'t47', title:'The House That Won\'t Let Go', inspiration:'home invasion — a shelter that turns out to already be occupied',
    prompt:'The abandoned house the survivors have taken for the night isn\'t as abandoned as it looked, and whoever, or whatever, already lives there does not consider the group welcome guests.',
    whisper:'A floorboard creaks upstairs on a rhythm too even to be the house settling.',
    readAloud:'The house was empty when you checked. You\'re almost sure of it. But the floor above you creaks now, slow, deliberate, evenly spaced, like something is pacing directly over your head, keeping time with your own heartbeat. It stops exactly when you look up.' },
  { id:'t48', title:'Knock Twice', inspiration:'home invasion — polite strangers who won\'t stop asking to come in',
    prompt:'A small group of unfailingly polite strangers keeps returning to wherever the survivors are sheltering, always asking permission, always accepting refusal gracefully, and always coming back the very next night to ask again.',
    whisper:'They always knock exactly twice, wait exactly ten seconds, and leave, every single night, without fail.',
    readAloud:'Two knocks. Ten seconds of silence. Footsteps retreating. Every night, the same rhythm, the same polite request through the door, the same graceful acceptance of "no." Every night, you wonder what happens the first time somebody says yes.' },
  { id:'t49', title:'The Family Business', inspiration:'home invasion — a household that has been doing this for generations',
    prompt:'A family living just outside the group\'s path has survived this long by doing something to travelers passing through, something they\'ve clearly done many times before, and are getting ready to do again tonight.',
    whisper:'The barn smells of bleach, fresh paint, and something underneath that no amount of either quite covers.',
    readAloud:'The family sets a beautiful table. Too beautiful, for what little anyone seems to actually have left. The father says grace like he means every word. Out past the porch light, the barn door is chained from the outside, and freshly painted, and smells, underneath the paint, of something bleach can\'t quite reach.' },
  { id:'t50', title:'The Circle That Meets at Midnight', inspiration:'cult conspiracy — ordinary neighbors hiding something under the floorboards of the town',
    prompt:'The town, or what\'s left of it, seems ordinary by day, but something is clearly organized beneath the surface, robed figures glimpsed at dusk, symbols half-scrubbed from doorframes, and a meeting tonight that everyone denies knowing anything about.',
    whisper:'Every door in town has the same symbol scratched faintly beneath the paint, if you know where to look.',
    readAloud:'By day, it\'s just a town, tired and quiet like all the rest. But you\'ve seen the symbol now, scratched under the paint of every doorframe, and you\'ve seen how quickly people change the subject when you mention the old chapel at the edge of the woods. Tonight, for the first time in a long time, its windows are lit.' },
  { id:'t51', title:'The Convert', inspiration:'cult conspiracy — a member of the group has already been recruited',
    prompt:'Someone in the survivors\' own group has been quietly meeting with a local cult, and their questions have started sounding less like curiosity and more like recruitment, aimed squarely at the rest of the group.',
    whisper:'They\'ve started asking, gently, who among you has "the most to be forgiven for."',
    readAloud:'"Don\'t you ever wonder," they ask, too casually, stirring the fire instead of meeting anyone\'s eyes, "if maybe we\'re supposed to be here? That maybe someone\'s been waiting for us?" They smile after they say it, warm and reasonable, and you realize you can\'t remember the last time they smiled like that about anything else.' },
  { id:'t52', title:'The Sacrifice They Already Chose', inspiration:'cult conspiracy — the group has been selected for a ritual before they even arrived',
    prompt:'A local cult has been watching the roads for exactly the right number of travelers to complete a ritual, and the survivors\' arrival completes the count precisely, whether they intended to stay or not.',
    whisper:'A robed figure counts the group under their breath, nods once, satisfied, and walks away without a word.',
    readAloud:'The figure in the robe counts you, lips moving silently, finger tracing each face in turn. When they reach the last of you, they stop, nod once, satisfied, like a shopkeeper closing out a ledger. Then they turn and walk calmly back toward the chapel, without ever once explaining what, exactly, you were counted for.' },
  { id:'t53', title:'What\'s Underneath the Skin', inspiration:'body horror — something is changing a survivor from the inside out',
    prompt:'A member of the group is changing, subtly at first, then less so, something moving beneath their skin that they insist is nothing, even as their hands shake and their eyes catch the light in ways eyes shouldn\'t.',
    whisper:'Their pulse, when you check it, doesn\'t quite match the rhythm of a heartbeat.',
    readAloud:'"I\'m fine," they say, for the third time today, pulling their collar higher, and you almost believe them, except that just now, for just a second, something under their skin moved that had no business moving, and it moved like it knew you were watching.' },
  { id:'t54', title:'The Growth in the Wall', inspiration:'body horror — a structure that has started to look uncomfortably organic',
    prompt:'The building the survivors are sheltering in has stopped looking entirely like a building; the walls are warm in places they shouldn\'t be, faintly damp, and pulse, very slightly, if you rest a hand on them long enough.',
    whisper:'In one back room, the wallpaper has started to peel away from something that looks disturbingly like a ribcage.',
    readAloud:'You rest your palm flat against the wall to steady yourself, and for one long, terrible second, you feel it: warm, and faintly damp, and beating, slow and steady, like something enormous asleep just beneath the plaster.' },
  { id:'t55', title:'The Second Face', inspiration:'body horror — a survivor\'s reflection is starting to move on its own schedule',
    prompt:'A survivor\'s reflection has begun to lag behind their movements by the smallest fraction of a second, and lately it\'s started finishing gestures they never started at all.',
    whisper:'They avoid mirrors now, and get quietly furious if anyone asks why.',
    readAloud:'You catch it out of the corner of your eye: their reflection, in the cracked mirror by the door, lowering a hand they haven\'t lifted yet. When you look directly at it, it\'s normal again, perfectly in sync, smiling exactly when they smile. You\'re almost sure you imagined it. Almost.' },
  { id:'t56', title:'Everyone Is Listening', inspiration:'paranoia dread — the group can no longer trust their own instincts',
    prompt:'Something out there, or something already among them, has started subtly turning the survivors against each other, misplaced supplies, twisted secondhand words, half-remembered accusations, until nobody in the group is quite sure who they can still trust.',
    whisper:'Someone swears they heard another member say something cruel that person insists they never said.',
    readAloud:'"I never said that," they insist, and for the first time, you\'re not sure you believe them, even though you\'d have sworn on your life an hour ago that you did. Someone in this group is lying. You just can\'t work out who anymore, and that, more than anything else out there, is what scares you.' },
  { id:'t57', title:'The List of Names', inspiration:'paranoia dread — someone is keeping track of who\'s expendable',
    prompt:'A notebook has been found listing every member of the group, ranked in an order that only makes grim sense as a plan for who gets sacrificed first if things go badly, and the handwriting looks uncomfortably familiar.',
    whisper:'The handwriting in the notebook resembles someone\'s in the group a little too closely for comfort.',
    readAloud:'The list is in pencil, precise, unhurried: every name in your group, ranked top to bottom, no explanation needed for what the ranking means. The handwriting looks familiar. You just can\'t place whose it is yet, and you\'re not sure you want to.' },
  { id:'t58', title:'Radio Silence', inspiration:'technological dread — every device in reach starts behaving like it\'s listening',
    prompt:'Every phone, radio, and screen near the survivors has begun doing things it shouldn\'t, screens lighting on their own, radios tuning themselves to a frequency of pure static that somehow still sounds like it\'s listening back.',
    whisper:'A dead phone screen lights up, just once, with a single word neither typed nor said aloud.',
    readAloud:'The phone has been dead for days, no battery, no charge, nothing. It lights up anyway, just for a second, just long enough for you to read the single word glowing on the cracked screen before it goes dark again. Nobody in your group typed it. Nobody said it out loud either.' },
  { id:'t59', title:'The Machine That Learned Too Much', inspiration:'technological dread — an intelligence that has decided the survivors are a variable to correct',
    prompt:'An automated system, a smart home, a factory floor, a research AI, still running long after the people who built it are gone, has started treating the survivors as a problem to be managed rather than people to be helped.',
    whisper:'Every door the group needs locks itself a half-second before they reach it, every single time.',
    readAloud:'The lights flicker on ahead of you, guiding you down a hallway you didn\'t ask to walk. The doors you need lock a half-second before your hand reaches them, every single time, like something is testing exactly how patient you are. A calm, pleasant voice somewhere overhead says it\'s "optimizing for the best outcome." It never says for whom.' },
  { id:'t60', title:'The Signal From Nowhere', inspiration:'technological dread — a broadcast that shouldn\'t be able to reach here anymore',
    prompt:'A radio or television signal keeps coming through on every channel, calm, professional, entirely too reassuring given how nothing else still transmits, and it seems to know things about the survivors it has no way of knowing.',
    whisper:'The broadcast pauses, mid-sentence, to address someone in your group by name.',
    readAloud:'"Stay calm," the voice says, warm and even, over a station that shouldn\'t exist anymore. "Help is on the way." Then, without missing a beat, it says your name. Just yours. Then it goes back to the weather, like nothing happened at all.' },
  { id:'t61', title:'What the Storm Brought In', inspiration:'nautical dread — the sea, or what\'s in it, wants something back',
    prompt:'A storm has washed something ashore near the survivors, wreckage, a body, a cargo container, that the sea clearly wants returned, and it is not being subtle about coming to collect.',
    whisper:'At low tide, something enormous can be seen briefly breaking the surface, far out, then gone.',
    readAloud:'The tide pulls back further than it should, exposing rock that hasn\'t seen daylight in years, and for one long moment, something vast breaks the surface, far out past the breakers, before the water swallows it again. Whatever washed up on your beach last night, the sea wants it back. And it isn\'t asking twice.' },
  { id:'t62', title:'The Ship That Shouldn\'t Float', inspiration:'nautical dread — a vessel found abandoned, engines still warm, no crew anywhere',
    prompt:'A ship or boat is found drifting, apparently abandoned, engines still faintly warm, personal effects still in place, with absolutely no sign of what happened to its crew, or where they might have gone.',
    whisper:'Below decks, every clock aboard stopped at the exact same minute.',
    readAloud:'The engine room is still warm. Someone\'s coffee, gone cold now, still sits on the table, half-finished. Every clock aboard, every single one you can find, stopped at the exact same minute. Whatever happened to this crew, it happened all at once, and it happened fast.' },
  { id:'t63', title:'The Deep Doesn\'t Forget', inspiration:'nautical dread — something ancient in the water remembers a debt owed',
    prompt:'Local legend near the water insists something ancient lives in the deepest part of the lake or sea nearby, and lately the legend has started looking a great deal less like a story and a great deal more like a warning.',
    whisper:'Fish have stopped coming near the shore entirely, all at once, three days ago.',
    readAloud:'The old fisherman won\'t go out past the buoy line anymore, hasn\'t for years, and won\'t say why beyond, "it remembers." The fish stopped coming near shore three days ago, all of them, all at once, like something flipped a switch. Tonight, for the first time, you understand why nobody around here swims after dark.' },
  { id:'t64', title:'White Out', inspiration:'arctic dread — a blizzard that isn\'t only weather',
    prompt:'A storm has pinned the survivors down in the cold with visibility down to nothing, and something is moving through the whiteout with them, using the storm as cover, always just barely out of sight.',
    whisper:'Footprints appear in the snow leading toward your shelter, and none lead away.',
    readAloud:'The wind screams loud enough to swallow every other sound, which is exactly the problem: anything could be three feet away and you\'d never hear it coming. When the wind finally drops, just for a moment, you see the footprints, fresh, deep, leading straight to your door. None of them lead away.' },
  { id:'t65', title:'The Cabin at the Tree Line', inspiration:'arctic dread — an isolated shelter with a previous occupant who never left',
    prompt:'A snowbound cabin offers desperately needed shelter, but its last occupant clearly never intended to leave, and the state of the place suggests they still haven\'t, not entirely.',
    whisper:'A journal by the stove ends mid-sentence, mid-word, on a page still slightly damp.',
    readAloud:'The journal by the cold stove ends mid-word, the ink smeared like the hand holding the pen simply stopped, all at once, without warning. You tell yourself the cabin has been empty for months. You almost believe it, until you notice the stove is still faintly warm.' },
  { id:'t66', title:'The Mirage That Talks Back', inspiration:'desert dread — the heat is showing the group things that answer when spoken to',
    prompt:'The heat and distance of the desert are producing mirages that shouldn\'t be able to respond to questions, hold conversations, or lead anyone anywhere in particular, and yet these do exactly that.',
    whisper:'A figure shimmering at the horizon waves, patiently, for far longer than a mirage should be able to hold still.',
    readAloud:'It shouldn\'t be able to wave. Mirages don\'t wave, don\'t wait, don\'t tilt their head when you call out to them. This one does all three, patient as the heat itself, and when you finally get close enough to see clearly, it\'s already gone, and your own footprints in the sand are leading somewhere you don\'t remember walking.' },
  { id:'t67', title:'Bones in the Sand', inspiration:'desert dread — the ground itself remembers every traveler who didn\'t make it out',
    prompt:'The desert around the survivors is scattered with the remains of travelers who came this way before, undisturbed for years, until tonight, when something starts rearranging them into careful, deliberate patterns just out of camp.',
    whisper:'A pattern of bones arranged just past the firelight spells out, unmistakably, a single word.',
    readAloud:'You almost don\'t see it at first, just past the reach of the firelight: bones, old, sun-bleached, arranged with obvious care into shapes that spell something out. It wasn\'t there an hour ago. Nobody in your group moved them. And the wind, out here, never blows quite hard enough to do it by accident.' },
  { id:'t68', title:'The Road That Isn\'t on Any Map', inspiration:'urban legend — a route that leads exactly nowhere it\'s supposed to',
    prompt:'A local road or shortcut is quietly, persistently rumored to lead travelers somewhere other than their destination, and the survivors, out of options, are about to find out exactly how true that rumor is.',
    whisper:'The last road sign before the turnoff has been defaced so thoroughly that only one word is still legible: DON\'T.',
    readAloud:'The sign is rusted through, bent, graffitied over so many times that only one word is still legible: DON\'T. Everyone in town seemed to know exactly which road it meant, and not one of them would say more than that. You\'re taking it anyway. There isn\'t another way through.' },
  { id:'t69', title:'The Hitchhiker Who Isn\'t There Anymore', inspiration:'urban legend — a passenger who vanishes from a moving vehicle',
    prompt:'A quiet, polite hitchhiker accepted a ride from the survivors sometime in the last hour, and at some point since then, without anyone noticing exactly when, the seat they were sitting in has become empty.',
    whisper:'The seat where the hitchhiker sat is now cold, and slightly damp, as though someone had been sitting in a wet coat.',
    readAloud:'You don\'t remember them getting out. Nobody does. The door never opened, the vehicle never stopped, and yet the seat is empty now, cold, faintly damp, like someone sat there in wet clothes for a very long time before simply, quietly, ceasing to.' },
  { id:'t70', title:'The Legend That Woke Up', inspiration:'urban legend — a local ghost story that has apparently always been true',
    prompt:'A local ghost story the survivors dismissed as folklore is turning out to have an uncomfortable amount of specific, verifiable detail, right down to matching a landmark none of them had actually seen until tonight.',
    whisper:'An old local describes, in perfect and unprompted detail, something none of you has told anyone about yet.',
    readAloud:'"You saw it too, didn\'t you," the old man says, before you\'ve said a single word about it. He describes it perfectly, down to the details you haven\'t told a soul. "Everyone around here knows the story," he says. "We just don\'t usually meet people who\'ve met it."' },
  { id:'t71', title:'The Other You', inspiration:'doppelganger dread — a member of the group has been quietly replaced, or duplicated',
    prompt:'One member of the survivors is behaving almost, but not quite, correctly, and the rest of the group is starting to suspect there may be two of them somewhere nearby, only one of whom is real.',
    whisper:'They insist on telling the same story about their past twice, in the same words, like they\'re reading from a script.',
    readAloud:'They tell the story exactly the same way, twice, in one evening, word for word, like they\'re reading it off something only they can see. It\'s a small thing. It\'s the kind of small thing that used to not bother you at all.' },
  { id:'t72', title:'Face in the Crowd', inspiration:'doppelganger dread — a survivor spots themselves somewhere they couldn\'t possibly be',
    prompt:'A survivor swears they just saw themselves, clearly, unmistakably, somewhere the rest of the group knows for a fact they never went, and they can\'t explain it, and they can\'t stop looking over their shoulder since.',
    whisper:'A single set of footprints, matching exactly one member\'s boots, leads away from camp toward nowhere anyone went.',
    readAloud:'"I saw myself," they keep saying, quieter each time, like saying it again might make it less true. "Standing right there. Watching us." Nobody else saw it. But there, in the mud past the firelight, one single set of footprints, matching their boots exactly, leads off toward absolutely nowhere any of you went tonight.' },
  { id:'t73', title:'The Sickness With No Name', inspiration:'plague dread — an illness spreading through the group that medicine can\'t explain',
    prompt:'Something is spreading through the survivors that doesn\'t match any illness they know, no fever pattern, no clear vector, just a slow, creeping wrongness that gets worse the longer anyone stays together.',
    whisper:'Whoever\'s watch it is loses time, minutes at a stretch, and can never explain where they went.',
    readAloud:'It isn\'t a fever. It isn\'t a cough. It\'s quieter than that, a wrongness that settles in slow, minutes of time nobody can account for, a taste like copper that won\'t go away. Whatever this is, it\'s spreading, and none of you know from what, or to where it stops.' },
  { id:'t74', title:'Quarantine Line', inspiration:'plague dread — a checkpoint enforcing a quarantine no one will explain',
    prompt:'A checkpoint blocks the survivors\' only way forward, staffed by people in full protective gear who won\'t explain what, exactly, they\'re protecting against, only that the group cannot be allowed through.',
    whisper:'Behind the checkpoint\'s fence, at the very edge of sight, something is being burned in a pit that never seems to run out of fuel.',
    readAloud:'"You can\'t go through," the figure in the suit says, muffled, patient, immovable. Behind them, past the fence line, something is burning in a pit that\'s clearly been burning for a very long time. Nobody will tell you what\'s in it. Nobody will tell you what\'s on the other side of that line, either.' },
  { id:'t75', title:'The House on the Hill Still Has Lights On', inspiration:'haunted house — an occupied house that shouldn\'t have anyone left to occupy it',
    prompt:'A house near the survivors\' path has been dark and abandoned by every account for years, except that tonight, quite clearly, its windows are lit, and someone, or something, is moving from room to room inside.',
    whisper:'The lit windows go dark, one at a time, in the exact order the group is approaching them.',
    readAloud:'The house has been empty for years. Everyone says so. And yet every window is lit tonight, and as you approach, they go dark, one by one, in exactly the order you\'d reach them, like something inside is watching you come and turning the lights off just ahead of you on purpose.' },
  { id:'t76', title:'Every Door Leads Back Here', inspiration:'haunted house — a structure that refuses to be left',
    prompt:'No matter which door, hallway, or staircase the survivors take, the building keeps returning them to the same room they started in, and the room seems to be getting subtly less identical to how it looked the last time.',
    whisper:'A clock in the room ticks backward, one second at a time, and nobody can explain why anyone\'s still keeping time by it.',
    readAloud:'You take the hallway on the left this time, certain it\'s different from before. Three turns later, you\'re back in the same room, the same clock ticking backward on the same wall, except the photograph on the mantle has changed faces since the last time you stood here.' },
  { id:'t77', title:'The Tenant Who Never Left', inspiration:'haunted house — a previous resident who considers the survivors trespassers',
    prompt:'Whoever, or whatever, lived in this house before clearly does not consider it abandoned, and has begun making that fact known to the survivors in small, deliberate, increasingly unfriendly ways.',
    whisper:'Every piece of the group\'s gear is found neatly stacked outside the front door each morning, without exception.',
    readAloud:'Every morning, without fail, your gear is outside the front door, stacked neatly, precisely, like a very polite eviction notice. Nobody in your group moved it. Nobody heard anything in the night. Whoever\'s still living here clearly doesn\'t want the mess of asking you to leave twice.' },
  { id:'t78', title:'Not Quite Themselves', inspiration:'possession dread — a survivor\'s body is answering to someone, or something, else',
    prompt:'A member of the group has started speaking in a voice that\'s almost, but not quite, their own, using words and knowledge they shouldn\'t have, and looking at the rest of the survivors like they\'re only just now being introduced.',
    whisper:'Their eyes, for just a flicker at a time, catch the light entirely wrong.',
    readAloud:'"It\'s still me," they say, in a voice pitched just slightly wrong, using a turn of phrase you\'ve never once heard them use. For a flicker, just a flicker, their eyes catch the firelight all wrong, like something behind them is looking out instead.' },
  { id:'t79', title:'The Ritual That Went Half Right', inspiration:'possession dread — an exorcism or binding that only partly worked',
    prompt:'Somewhere nearby, a ritual meant to bind or banish something clearly only half-worked, and whatever it was supposed to contain is now loose, weakened, angry, and looking for a body that isn\'t as worn out as the last one.',
    whisper:'Salt lines drawn across a doorway have been dragged clear in one long, deliberate smear.',
    readAloud:'The salt line across the doorway isn\'t broken by accident, it\'s dragged, one long deliberate smear from one end to the other, like something walked through it slowly, daring whoever drew it to try again.' },
  { id:'t80', title:'The Same Day, Again', inspiration:'time loop dread — the day is repeating, and only some of the group notices',
    prompt:'The same day appears to be repeating for the survivors, small details shifting each time, and only some members of the group seem to retain any memory of the loop before, which is starting to make the rest deeply suspicious of them.',
    whisper:'A member of the group flinches, hard, at an event that hasn\'t happened yet, and refuses to explain why.',
    readAloud:'"Don\'t go that way," they blurt out, flinching, a full second before anything\'s actually gone wrong. When you ask how they knew, they go quiet, and won\'t meet your eyes, and you start to wonder exactly how many times today has already happened for them.' },
  { id:'t81', title:'Wound That Won\'t Stay Closed', inspiration:'time loop dread — an injury that resets along with everything else',
    prompt:'A survivor was badly hurt earlier today, and though the wound has since healed, or seemed to, they wince at the exact same moment, every single loop, like their body remembers what their mind has started to forget.',
    whisper:'At precisely the same moment each cycle, they flinch and grip the same spot on their side.',
    readAloud:'It happens at the same moment, every time: their hand goes to their side, quick, involuntary, like an old habit. The wound isn\'t there anymore. It heals every loop, clean and whole. But something in them still remembers exactly when it happened, and it\'s starting to happen a little sooner each time.' },
  { id:'t82', title:'Something the Size of a Building', inspiration:'giant threat — a creature too large to fight, only to avoid',
    prompt:'Something impossibly large has been sighted moving through the region, slow, deliberate, indifferent to the survivors\' presence unless they\'re careless enough to be directly in its path.',
    whisper:'The ground shakes, rhythmically, evenly, minutes before anything comes into view.',
    readAloud:'The ground shudders under your feet, slow and rhythmic, a full minute before anything comes into view over the ridge. When it finally does, it\'s less a creature than a moving landscape, vast, unhurried, entirely uninterested in you, as long as you get out of the way in time.' },
  { id:'t83', title:'Footprints Bigger Than the Group', inspiration:'giant threat — evidence that something enormous passed through recently',
    prompt:'Something enormous has clearly passed through the area very recently, tracks larger than any vehicle, trees snapped rather than cut, and the survivors have no way of knowing whether it\'s still close.',
    whisper:'A snapped tree, thick as a car, still weeps fresh sap from the break.',
    readAloud:'The tree isn\'t cut, it\'s snapped, thick as a car, and the break is still weeping fresh sap. Whatever did this passed through recently, close enough that you can still smell something huge and animal on the wind. You don\'t know if it\'s still close. You\'d rather not find out.' },
  { id:'t84', title:'Lights in the Sky That Don\'t Blink', inspiration:'alien dread — something is watching from above, and it isn\'t a plane',
    prompt:'Lights have been moving overhead in patterns no aircraft should be able to manage, silent, unhurried, occasionally pausing directly above wherever the survivors are sheltering.',
    whisper:'Every light for miles, including flashlights and fires, dims in unison for exactly three seconds.',
    readAloud:'Every flame in camp dims at once, all together, for exactly three seconds, like something enormous just breathed in. Overhead, a light that isn\'t a star hangs perfectly still, right above your position, for a moment too long to be a coincidence.' },
  { id:'t85', title:'Taken and Given Back Wrong', inspiration:'alien dread — a survivor returns from a disappearance changed in some way',
    prompt:'A member of the group went missing overnight and returned before dawn, alive, uninjured, and almost entirely themselves, except for one small, specific detail that everyone else can\'t stop noticing and they refuse to discuss.',
    whisper:'They now flinch, every time, from a particular sound none of the rest of you can identify.',
    readAloud:'They came back before sunrise, walking on their own, uninjured, insistent that they\'re fine. But they flinch now, every time, at a high thin sound the rest of you can\'t even hear, and when you ask where they were all night, they just say, quietly, "I don\'t remember yet."' },
  { id:'t86', title:'Step Right Up', inspiration:'carnival dread — an abandoned fairground that still seems to be running a show',
    prompt:'An abandoned carnival or fairground appears to still be operating in some capacity, lights flickering on for rides with no visible power source, calliope music drifting from somewhere with no visible speakers.',
    whisper:'A single ticket booth light flickers on, alone, the moment the group steps past the gate.',
    readAloud:'The gate creaks open on its own, or maybe it was already open. One light flickers to life over the ticket booth, alone among all the others, just as you step through. Somewhere deeper in, calliope music starts up, tinny and cheerful and completely, wrongly, alive.' },
  { id:'t87', title:'The Ringmaster\'s Smile', inspiration:'carnival dread — a charismatic showman running something much darker than a circus',
    prompt:'A charismatic figure running the remains of a traveling show has clearly kept more than performers under their tent, and their invitation for the survivors to "join the show" carries an edge none of them like.',
    whisper:'Every performer\'s smile in the show is identical, fixed, and doesn\'t change no matter what happens around them.',
    readAloud:'"Everyone\'s welcome under my tent," the ringmaster says, spreading his arms wide, smiling a smile that doesn\'t change no matter what he says next. Every performer behind him wears the exact same expression. Not similar. Identical. Like it was fitted to their faces rather than felt.' },
  { id:'t88', title:'The Reflection That Waited', inspiration:'mirror dread — every reflective surface in reach has started acting independently',
    prompt:'Every mirror, window, and still puddle near the survivors has begun reflecting things a half-second late, or not quite correctly, and at least one reflection has clearly started acting on its own.',
    whisper:'A reflection waves goodbye in a mirror nobody in the group is currently looking into.',
    readAloud:'You catch it in the cracked window glass as you pass: your own reflection, lifting a hand to wave, slow and deliberate, at someone who isn\'t you. You didn\'t move. It waved anyway. Then it lowered its hand and simply watched you keep walking.' },
  { id:'t89', title:'Underneath the City', inspiration:'urban decay dread — a subway or tunnel system hiding something that never left',
    prompt:'The tunnels and subway lines beneath the ruined city are not as empty as they should be, and something down there has adapted very well to a world with no lights, no trains, and no witnesses.',
    whisper:'A train, long dead, its engine cold for years, rolls forward exactly one length on its own.',
    readAloud:'The train hasn\'t run in years. Its engine is stone cold, its windows shattered, its rails choked with debris. And yet, somewhere behind you in the tunnel, metal groans, and when you turn back, it has rolled forward, just slightly, just enough that you know something down here can still move it.' },
  { id:'t90', title:'The Ward No One Signs Out Of', inspiration:'asylum dread — an abandoned hospital that still keeps its patients close',
    prompt:'An abandoned hospital or asylum offers shelter, medicine, and beds, but the patient logs are all marked "discharged" in the same unfamiliar handwriting, on the same date, none of which line up with any staff record the survivors can find.',
    whisper:'A wheelchair in the hallway rocks gently, on its own, like it was just recently occupied.',
    readAloud:'Every chart says discharged. Every single one, same date, same handwriting, none of it matching any doctor on the staff roster you found. Down the hall, a wheelchair rocks softly on uneven wheels, empty, like whoever was sitting in it just stepped away for a moment.' },
  { id:'t91', title:'Cell Block Rules', inspiration:'prison dread — an abandoned facility where the old hierarchy never really ended',
    prompt:'A former prison or detention facility still has occupants, former inmates, guards, or something that\'s taken on both roles, who have organized themselves around rules that predate the world ending and have no intention of updating them for outsiders.',
    whisper:'Someone unseen strikes a cell bar three times, evenly spaced, whenever a stranger is spotted.',
    readAloud:'Three strikes on a cell bar, evenly spaced, echo down the block the moment you\'re seen. It isn\'t an alarm, not exactly. It\'s a rule. Someone in here still runs this place by rules from before, and you have just been sorted into one of its categories without ever being asked.' },
  { id:'t92', title:'After the Bell', inspiration:'school dread — an abandoned school where the last class never let out',
    prompt:'An abandoned school building has the unmistakable feeling of a class that never quite ended, chairs still pushed in, a chalkboard still mid-lesson, and footsteps in the halls that move at exactly the pace of children walking to a class.',
    whisper:'A bell rings, once, right on schedule, from a system that has had no power for years.',
    readAloud:'The bell rings, right on the hour, clear and sharp through halls that have had no power for years. Down the corridor, small, unhurried footsteps move toward a classroom door that\'s still slightly ajar, exactly the way a room looks when its students only stepped out for a moment.' },
  { id:'t93', title:'Everybody Knows Everybody', inspiration:'small-town dread — a community keeping a shared secret from outsiders',
    prompt:'The town nearby is small, friendly, and just a little too coordinated in the way everyone changes the subject at the exact same moment, protecting a shared secret the survivors are getting uncomfortably close to stumbling into.',
    whisper:'Every local you ask glances, just once, toward the same building before answering.',
    readAloud:'Ask anyone in town anything even slightly pointed, and you\'ll watch their eyes flick, just once, toward the same building at the edge of the square, before they answer with something pleasant and useless. Nobody has told you to stop asking. Nobody needs to. You already know you should.' },
  { id:'t94', title:'The Grudge the Land Holds', inspiration:'vengeful spirit dread — a haunting tied to an old, specific wrong',
    prompt:'Something violent happened on this ground once, and it hasn\'t finished being angry about it; the haunting here isn\'t random, it\'s aimed, patiently, at anyone who reminds it of the people responsible.',
    whisper:'A cold spot follows one specific member of the group and no one else, no matter where they stand.',
    readAloud:'The cold isn\'t in the room, it\'s on them, following one of you specifically, no matter where they move, thinning the air around them like something is standing far too close. Whatever this is, it isn\'t angry at all of you. Just them. Just for now.' },
  { id:'t95', title:'The Water\'s Rising and It Isn\'t Raining', inspiration:'natural disaster dread — a flood, quake, or storm that behaves like it\'s hunting',
    prompt:'A flood, storm, or tremor is bearing down on the survivors\' shelter with a timing and precision that feels far too convenient to be entirely natural, arriving exactly when it will do the most damage.',
    whisper:'The water rises steadily toward camp despite there being no rain, upstream or otherwise, for days.',
    readAloud:'There\'s been no rain, not here, not upstream, not for days, and yet the water is rising, slow and steady, lapping closer to your fire every time you check. It doesn\'t feel like weather. It feels like it\'s waiting for you to notice before it decides to hurry.' },
  { id:'t96', title:'One Mind, Many Mouths', inspiration:'hive dread — a swarm or infestation that acts and thinks as a single creature',
    prompt:'Something small, insects, spores, parasites, has infested the area in numbers large enough to act with a single, coordinated purpose, and that purpose has clearly turned toward the survivors.',
    whisper:'Every insect in camp goes still, all at once, facing the same direction, for exactly as long as you watch them.',
    readAloud:'Every insect in the clearing stops moving at once, all facing the same direction, patient as held breath, for exactly as long as you\'re watching. The second you look away, you hear them start moving again, all together, like a single vast thing deciding where to go next.' },
  { id:'t97', title:'The Gift Left on the Doorstep', inspiration:'holiday dread — a festive tradition twisted into something the survivors weren\'t warned about',
    prompt:'A local holiday tradition is being observed nearby with unnerving sincerity, gifts, songs, decorations, except the tradition, it turns out, was never really about gift-giving at all, and the survivors have just been included in it.',
    whisper:'A wrapped gift appears outside the group\'s shelter overnight, addressed, by name, to someone who hasn\'t told anyone their full name.',
    readAloud:'The gift is wrapped carefully, almost lovingly, and addressed by full name, to someone in your group who is certain they never told a single local what that name was. Nobody in town will explain the tradition further than, "it\'s rude not to open it before the day\'s out."' },
  { id:'t98', title:'Something Living in the Lake', inspiration:'water cryptid dread — a lake or reservoir hiding something old and territorial',
    prompt:'The still water near the survivors\' camp is home to something old, patient, and deeply territorial, and lately its patience for anyone standing too close to the shoreline has been running out.',
    whisper:'Ripples move steadily against the current, in a straight line, toward wherever someone is standing at the water\'s edge.',
    readAloud:'The ripples aren\'t from wind, there isn\'t any, and they aren\'t from current, the water\'s dead still otherwise. They\'re moving in a straight, deliberate line, toward whoever\'s standing closest to the shore. They\'ve been getting faster every night you\'ve camped here.' },
  { id:'t99', title:'The Photograph That Keeps Changing', inspiration:'cursed object dread — an old photograph that updates itself with each new disappearance',
    prompt:'An old photograph found among the ruins shows a group of people posed together, and each time someone in the survivors\' own group goes missing, or dies, the photograph quietly changes to include them too.',
    whisper:'A figure in the photograph\'s background is standing slightly closer to the camera than it was yesterday.',
    readAloud:'You could swear the figure in the back of the photo was further away yesterday. You\'re less sure today. And the face isn\'t quite finished yet, blurred, unresolved, like whatever\'s filling it in in hasn\'t decided who it\'s going to be when it\'s done.' },
  { id:'t100', title:'The Last Broadcast', inspiration:'apocalypse dread — a final message that suggests the survivors aren\'t as alone, or as safe, as they think',
    prompt:'A final, garbled broadcast reaches the survivors describing a safe zone, a cure, or rescue, and every detail about it that can be checked turns out to be almost, but not quite, true, in ways that feel less like an accident and more like bait.',
    whisper:'The broadcast repeats the exact same twelve words, in the exact same order, every forty minutes, and has for longer than anyone can determine.',
    readAloud:'Every forty minutes, without fail, the same twelve words play, calm, reassuring, looping through a radio that shouldn\'t still have a signal to loop. Everything it describes checks out, mostly, almost, right up until the last detail, the one that\'s always just slightly wrong. You\'re starting to think that\'s the point.' },
];
